### ISSUE TITLE
reference SV dataset for NA12878

### ISSUE THREAD

**Issue by Manuelaio** [stat-lab/EvalSVcallers#16]
Hello, 
I'm trying to reproduce the results of precision and recall of different algorithms explained in your papers on real data (for instance NA12878), unfortunately I find results extremely different especially for duplication precision/recall. Where Can I find the Reference SV dataset for real data used in your study? It would be great if you could provide this set of data in order to reproduce your results. Many many thanks.

**Comment by stat-lab** [comment]
You can find it (Ref_SV/NA12878_DGV-2016_LR-assembly.vcf) in the EvalSVcallers package. For evaluation of DUP calls, the script (evaluate_SV_callers.pl) tries to examine whether the breakpoints of a DUP call match the breakpoints of the reference INS data if a DUP call does not match the reference DUPs. Because DUPs are a kind of INSs, a fraction of INSs in the reference SV data could contain DUPs.

**Comment by Manuelaio** [comment]
Thank you so much for your replay! manuela
